### ISSUE TITLE
[FEAT] User must be able to get, update, and add music cover as they add a new music.

### ISSUE THREAD

**Issue by Krr0ptioN** [Krr0ptioN/musica#10]
### Feature Description

**Summary:**
User will be able to see the cover of the musics, and while adding new music he can provide cover if in case s/he wanted to change the music cover.

**Acceptance Criteria:**
1. The music cover in music player must change while playing another music.
2. The music player should use a default music cover if the music lack cover.
3. The music cover must stay constant as other the properties the music object unless the user aim to change the music properties.

<details><summary>Details</summary>
<p>

### **Additional Details:**

**UI Specification:** 
- UI components are already built
- Redux frontend storage lib must be updated to support music cover as state for music

**Technical Interface Specification:**
- `POST /music/` must be handle another file in case it is provided as cover.
- New file storage directory must be created and handled
- A new endpoint for retrieving the music cover file.

### **Tasks:**
- [X] `POST /music/` must be handle another file in case it is provided as cover.
- [X] New file storage directory must be created and handled
- [X] A new endpoint for retrieving the music cover file.
- [X] Redux frontend storage lib must be updated to support music cover as state for music

**Related Links/Dependencies:**
- #14 
   - Consider that later the covers must be retrievable by other component such as tabbed sidebar while preseting the list view of musics.
- #15 
   - User the form will utilize the create endpoint to add music cover.

### Quality Assurance

- [X] Unit tests are created/updated.
- [X] Integration tests (if applicable) are performed.
- [X] API end points are documented

</p>
</details>
