### ISSUE TITLE
[FEAT] User wants to be able to create and add new musics to the Musica through a form by clicking a [ + ] add button.

### ISSUE THREAD

**Issue by Krr0ptioN** [Krr0ptioN/musica#15]
### User Story/Feature Description

**Summary:**
Just below the sidebar there is a button where user click and a new form pop up, which enables the user to add new music with related information.

### **Tasks:**
- [ ] Drop down component
- [ ] Search field component
- [ ] Form widget 
- [ ] Converting the widgets and components to a library in **nx**.
- [ ] Caching the files initally for Redux instead of retrieving them back from the server after the creation.

### Quality Assurance

- [ ] Unit tests are created/updated.
- [ ] Integration tests (if applicable) are performed.
- [ ] Documentation (if applicable) is updated.

<details><summary>Details</summary>
<p>

### **Additional Details:**

**UI Specification:**
- The form must not fill all of the screen and the background must be blurred.
- The add button attracts attention convey its role as the user sees it.
- The playlist, album, are selected through a drop down component while the artist throw a search field component.

**Technical Interface Specification:**
- **OPTIM** When the application was successfully created, add the music cover and file to the Redux locally instead of the retrieving it from the server.

**Related Links/Dependencies:**
- This issue has to be completed before the #14 

</p>
</details>
