### ISSUE TITLE
[REFACTOR] Return Message Key instead of raw text message in API response

### ISSUE THREAD

**Issue by Krr0ptioN** [Krr0ptioN/musica#18]
### Return Message Key instead of raw text message in API response

**Summary:**

Instead of return raw text message such as
```typescript
class Controller {
    create(){
        return {
           success: true,
           message: "Create object was sucessful ..."
        }
    }
}
```

We can utilize messageKey which can be documented, generalized and internationalized.
```typescript
class Controller {
    create(){
        return {
           success: true,
           messageKey: "CREATE_OBJECT"
        }
    }
}
```

### **Tasks:**
- [ ] Central document as single source of truth.
- [ ] Collect a list of messages by following CQRS design pattern
- [ ] Create document complication and deployment for documentation app
- [ ] Provide the means of internalization for translators

**Related Links/Dependencies:**
- [Link to related issues, pull requests, or documents]
- [Any dependencies that need to be resolved before starting this]

### Quality Assurance
- [ ] Documentation (if applicable) is updated.
