### ISSUE TITLE
[FEAT] Show a default music logo and loading or waiting while no music is selected to be played

### ISSUE THREAD

**Issue by Krr0ptioN** [Krr0ptioN/musica#33]
**Summary:**
Introduce a default music logo and loading indicator to be displayed when no specific music is selected for playback.

As a user exploring the music player interface, I want to see a default music logo and a loading/waiting indicator when no music is selected. This provides visual feedback, indicating the absence of selected music and assures me that the application is ready for interaction.

**Acceptance Criteria:**
1. A default music logo is displayed when no specific music is selected.
2. A loading or waiting indicator is shown to indicate the system's readiness for user interaction.
3. The default music logo and loading indicator disappear upon selecting and loading a music track.

### **Additional Details:**
**UI Specification:**
- The default music logo should be visually appealing and identifiable.
- The loading indicator should be clear and unobtrusive.
- Ensure smooth transition between the default music logo, loading state, and actual music playback.

**Technical Interface Specification:**
- Implement logic to detect the absence of selected music and trigger the display of default visuals.
- Utilize appropriate loading mechanisms to maintain a responsive user experience.
```typescript
  return (
    <div className="flex flex-col justify-between items-center rounded-xl sm:w-2/4 shadow-glass h-[30rem] bg-primary md:w-[390px]">
        // TODO: [FEAT] Show a default music logo and loading
        // or waiting while no music is selected to be played #33
        // TEST: The scenario where user selected no music so
        // it should face a loading state.
      <MusicPlayerCover src={playingMusic?.coverImageFileName} />
      {playingMusic ? (
        <MusicPlayerTitle
          name={playingMusic.name}
          artists={playingMusic.artists}
        />
      ) : (
        <MusicPlayerTitle
          name="Kill me right now"
          artists={['System of the Dawn']}
        />
      )}
```

**System level Specification:**
- Minimize resource usage during the loading state to ensure optimal system performance.
- Compatibility with various screen sizes and resolutions.

### **Tasks:**
- [ ] Design and implement the default music logo component.
- [ ] Integrate a loading or waiting indicator into the user interface.
- [ ] Implement logic to trigger the default visuals when no music is selected.

### Quality Assurance

- [ ] Unit tests are created/updated to validate the display of default visuals.
- [ ] Integration tests are performed to ensure smooth transitions and responsiveness.
- [ ] Documentation is updated to reflect the changes made to the Music Player UI.

### Notes
Consideration: User feedback on the visual appeal of the default music logo should be gathered during testing.
