### ISSUE TITLE
[DEV] Installer and setup script

### ISSUE THREAD

**Issue by Krr0ptioN** [Krr0ptioN/musica#37]
### Installer and setup script

**Summary:**
A software developer or someone who want's to setup this application, I want to have a script to automate setting up the app, configuring (env variables), and bootstrapping with different methods (docker, cloud, native, ...), so I have an easy time and standard steps of procedures while trying run this application.

**Acceptance Criteria:**
1. Interactive TUI and CLI interface
2. Configure the `.env` file
3. Provide scripts to start, stop, restart, and backup the application.

### **Additional Details:**
**UX Specification:**
- Use inquirer to provide a smooth and interactive experience for the developer

**Technical Interface Specification:**
- Use nestjs comandline application API and inquirer to interact with user.
- Provide range of options for deployment and execution

### **Tasks:**
- [ ] Designing the steps of script
- [ ] Developing the TUI interface using [Inquirer](https://github.com/SBoudrias/Inquirer.js)
- [ ] Developing the CLI interface 
- [ ] Module for setting up the application for native running
- [ ] Module for setting up the application for docker container running
- [ ] Deployment automation
- [ ] Backup automation using the provided API by `apps/api`

### Quality Assurance

- [ ] Manual Testing for features
- [ ] Documentation for usage of the script and it's options
